- name: Project Leaders
  files:
    - collaboration/collaboration.md
    - collaboration/leadership.md
    - project-design/project-design.md
    - project-design/pd-overview/pd-overview-planning.md
    - project-design/pd-overview/pd-overview-repro.md
    - project-design/pd-overview/pd-overview-methods.md
    - project-design/pd-overview/pd-overview-version.md
    - project-design/pd-design-overview/pd-checklist.md
    - project-design/pd-design-overview/project-repo.md
    - reproducible-research/reproducible-research.md
    - reproducible-research/overview/overview-definitions.md
    - reproducible-research/overview/overview-barriers.md
    - reproducible-research/open.md
    - reproducible-research/open/open-data.md
    - reproducible-research/open/open-source.md
    - communication/communication.md
    - communication/aa.md
    - communication/aa/aa-tips.md
  colour: purple
  description: >
    Project leaders are people who are responsible for project planning,
    resource allocation and other decision-making for and with the involvement
    of their project team. This curated set of chapters will point them to
    relevant tools and practices that they can use for managing their projects
    while ensuring transparency, reproducibility, collaboration and ethical
    practices throughout the lifecycle of research.
- name: Research Software Engineers
  files:
    - communication/citable.md
    - communication/citable/citable-otherscite.md
    - communication/citable/citable-cite.md
    - collaboration/collaboration.md
    - collaboration/research-infrastructure-roles.md
    - collaboration/research-infrastructure-roles/rse.md
    - collaboration/research-infrastructure-roles/rse-personal-story.md
    - collaboration/maintain-review.md
    - project-design/pd-design-overview/project-repo.md
    - project-design/pd-design-overview/project-repo/project-repo-advanced.md
    - reproducible-research/reproducible-research.md
    - reproducible-research/overview.md
    - reproducible-research/open.md
    - reproducible-research/open/open-data.md
    - reproducible-research/open/open-source.md
    - reproducible-research/vcs.md
    - reproducible-research/licensing.md
    - reproducible-research/code-quality.md
    - reproducible-research/testing.md
    - reproducible-research/reviewing.md
    - reproducible-research/renv.md
    - reproducible-research/binderhub.md
    - reproducible-research/ci.md
  colour: white
  description: >
    Research Software Engineers are programmers working in an academic context
    who play crucial roles in projects involving data and technology. This
    curated set of chapters will point them to open source and reproducibility
    practices important for working with data and developing software tools.
- name: Data Science Without Borders
  files:
    - reproducible-research/reproducible-research.md
    - reproducible-research/overview/overview-definitions.md
    - reproducible-research/vcs.md
    - reproducible-research/vcs/vcs-checklist.md
    - reproducible-research/open.md
    - reproducible-research/open/open-source.md
    - reproducible-research/open/open-data.md
    - reproducible-research/open/open-hardware.md
    - reproducible-research/open/open-access.md
    - reproducible-research/open/open-scholarship.md
    - reproducible-research/licensing.md
    - reproducible-research/rdm.md
    - reproducible-research/rdm/rdm-dmp.md
    - reproducible-research/rdm/rdm-fair.md
    - reproducible-research/rdm/rdm-metadata.md
    - reproducible-research/rdm/rdm-spreadsheets.md
    - reproducible-research/rdm/rdm-data-curation.md
    - reproducible-research/rdm/rdm-sharing.md
    - reproducible-research/rdm/rdm-checklist.md
    - reproducible-research/code-documentation.md
    - reproducible-research/testing.md
    - reproducible-research/testing/testing-overview.md
    - reproducible-research/testing/testing-checklist.md
    - reproducible-research/code-quality.md
    - reproducible-research/code-quality/code-quality-style.md
    - reproducible-research/reviewing/reviewing-workflow.md
    - reproducible-research/reviewing/reviewing-checklist.md
    - reproducible-research/code-reuse/code-reuse-details.md
    - project-design/project-design.md
    - project-design/pd-design-overview/pd-checklist.md
    - project-design/pd-design-overview/project-repo.md
    - project-design/info-management/filenaming.md
    - project-design/data-security/sdp.md
    - project-design/data-security/sdp/metadata.md
    - project-design/data-security/sdpm.md
    - project-design/data-security/sdpw.md
    - project-design/data-security/data-governance.md
    - project-design/missing-data.md
    - project-design/risks-of-bias.md
    - communication/communication.md
    - communication/os-comms.md
    - communication/dif-articles.md
    - communication/presentations.md
    - communication/research-objects.md
    - communication/citable/citable-steps.md
    - communication/aa.md
    - community-handbook/translation/translation-localisation.md
    - collaboration/remote-collab.md
    - collaboration/github-novice.md
    - collaboration/maintain-review.md
    - collaboration/organising-meetings.md
    - collaboration/coworking.md
    - collaboration/organising-conference.md
    - collaboration/chairing.md
    - collaboration/event-tools.md
    - collaboration/collaboration.md
    - collaboration/shared-ownership.md
    - collaboration/team-manual.md
    - collaboration/stakeholder-engagement.md
    - ethical-research/ethics-intro.md
    - ethical-research/law-policy.md
    - ethical-research/ethics-open-source-governance.md
    - ethical-research/cultural-change.md
  colour: green
  description: >
    For effective collaboration among international groups,
    such as in the Data Science Without Borders project,
    it is essential to learn, adopt, and implement best practices
    in open, reproducible, ethical, and inclusive data science.
    These curated chapters will provide starting points, helping
    you navigate a broader set of practices in The Turing Way.
