[build]
base = "book/"
command = "make deps && make ci"
environment = { PYTHON_VERSION = "3.13" }
publish = "website/_build/html"

# Do not build deploy previews for branches from all-contributors bot
[context.deploy-preview]
  ignore = '''
if echo $HEAD | grep "^all-contributors"; then
  return 0
else
  return 1
fi
'''

# A redirect rule with all the supported properties
[[redirects]]
  # Root page changed in https://github.com/the-turing-way/the-turing-way/pull/2994
  from = "https://the-turing-way.netlify.app/welcome"
  to = "https://book.the-turing-way.org/index.html"
  # The default HTTP status code is 301, but you can define a different one.
  status = 301
  force = true

# A redirect rule with all the supported properties
[[redirects]]
  # Root page changed in https://github.com/the-turing-way/the-turing-way/pull/2994
  from = "https://the-turing-way.netlify.app/welcome.html"
  to = "https://book.the-turing-way.org/index.html"
  # The default HTTP status code is 301, but you can define a different one.
  status = 301
  force = true
  
  # A redirect rule with all the supported properties
[[redirects]]
  from = "https://the-turing-way.netlify.app"
  to = "https://book.the-turing-way.org/index.html"
  # The default HTTP status code is 301, but you can define a different one.
  status = 301
  force = true

[[redirects]]
  from = "https://the-turing-way.netlify.app/introduction/*"
  to = "https://book.the-turing-way.org/index.html"
  # The default HTTP status code is 301, but you can define a different one.
  status = 301
  force = true

[[redirects]]
  from = "/version_control/*"
  to = "/reproducible-research/vcs"
  # The default HTTP status code is 301, but you can define a different one.
  status = 301
  force = true

[[redirects]]
  from = "/binderhub/*"
  to = "/reproducible-research/binderhub"
  # The default HTTP status code is 301, but you can define a different one.
  status = 301
  force = true
