contact_links:
  - name: "\u2615 Collaboration cafe"
    url: https://book.the-turing-way.org/community-handbook/coworking/coworking-collabcafe.html
    about: Sign up for mentored sprints and co-working sessions with Turing Way community members
  - name: "\U0001F5E3 All other questions and general chat"
    url: slack.the-turing-way.org
    about: Chat with the Turing Way community on Slack
