name: "\U0001F50D Editor's Issue Template"

# See the json schema to help you create / update this form
# https://json.schemastore.org/github-issue-forms.json

description: Template to propose editing a chapter

body:
  - type: markdown
    attributes:
      value:
        Please complete the following sections when you open an issue. You are
        encouraged to keep this top level comment box updated as you develop and
        respond to reviews. If you have write access to the repository please
        also assign the appropriate label (or labels) to your issue. Note that
        text within html comment tags will not be rendered.

  - type: textarea
    attributes:
      label: Summary
      description:
        Please provide a detailed description of the chapter/subchapter you
        propose to edit, review or restructure. Please provide as much context
        as possible and link to related issues and/or pull requests. Providing
        links to sections you're referencing for clarity is highly encouraged.
      render: markdown
      placeholder: "*Lorem ipsum dolor sit amet, consectetur adipiscing.*"
    validations:
      required: false

  - type: textarea
    attributes:
      label: What needs to be done?
      description: |
        In this section please comment on the overall structure of the file. Your response can cover the following questions: Do sections need clearer headings? Are there any technical terms that might not be understood? Is something missing that is worth discussing before adding?

        We suggest using bullets (indicated by * or -) and filled checkboxes [x].
        here.
      render: markdown
      value: |
        - [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*
        - [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*
    validations:
      required: false

  - type: textarea
    attributes:
      label: Who can help?
      description: |
        We suggest using bullets (indicated by * or -) and filled checkboxes [x].
        here.

        If you know the original author the chapter/section, it may be useful to tag them here for their input.
      render: markdown
      value: |
        - [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*
        - [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*
    validations:
      required: false

  - type: textarea
    attributes:
      label: Updates
      description:
        To avoid that others have to read through the full thread of comments,
        please update the initial issue with important updates (e.g. decisions
        taken) regularly. You can update the task list and summary above
        directly (this is encouraged!) or add new information below in this new
        section.
      render: markdown
      placeholder: "*Lorem ipsum dolor sit amet, consectetur adipiscing.*"
    validations:
      required: false
