name: CI

# run on pushes and pull requests to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "book/**"
      - ".github/workflows/**"
      - "ACCESSIBILITY.md"
      - "CONTRIBUTING.md"
      - "contributors.md"

# set the default shell to bash for all jobs
# this is important for the windows OS!
defaults:
  run:
    shell: bash

jobs:
  build-jb:
    name: Build
    if: (github.event.pull_request) && !contains(github.head_ref, 'all-contributors')
    strategy:
      matrix:
        # MacOS build is currently broken using JupyterBook2
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, windows-latest]
        python_version: ["3.13"]
      fail-fast: false # Don't cancel all jobs if one fails

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout-repository
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: make deps
        working-directory: ./book

      - name: Build Jupyter-Book with warnings raised to errors
        run: make ci
        working-directory: ./book
